# Mostrar solo WARN o ERROR por defecto
org.slf4j.simpleLogger.defaultLogLevel=warn

# Para mostrar más INFO de la app:
# org.slf4j.simpleLogger.log.com.tpo=info

# Silenciar MongoDB driver INFO:
org.slf4j.simpleLogger.log.org.mongodb.driver=warn

# Silenciar Cassandra driver INFO:
org.slf4j.simpleLogger.log.com.datastax=warn

# Silenciar HikariCP INFO:
org.slf4j.simpleLogger.log.com.zaxxer.hikari=warn
